version: '3.0'

services:
  mariadb:
    image: mariadb:Incetpion
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - maria-database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - Inception_Network
    restart: always

  wordpress:
    image: wordpress:Incetpion
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-database:/var/www/html
    env_file:
      - .env
    networks:
      - Inception_Network
    restart: always

  nginx:
    image: nginx:Incetpion
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress-database:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - Inception_Network
    container_name: nginx
    restart: always

volumes:
  maria-database:
    name: Maria_Database_Inception
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/maria-db

  wordpress-database:
    name: Wordpress_Database_Inception
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress-db

networks:
  Inception_Network:
    name: Inception_Network
    driver: bridge
