version: '3.0'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - maria-database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-net
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-database:/var/www/html
    env_file:
      - .env
    networks:
      - app-net
    restart: always

  nginx:
    image: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress-database:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - app-net
    container_name: nginx
    restart: always

volumes:
  maria-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/database/maria-db

  wordpress-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/database/wordpress-db

networks:
  app-net:
    driver: bridge
